name: Run Streamlit App with Groq

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: 🧪 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: ✅ Run Streamlit App (for test)
        run: |
          echo "Running Streamlit in test mode..."
          streamlit run your_script_name.py &
          sleep 10
          pkill streamlit
